import {DataAPI} from "./data.js";
import {runBacktest} from "./backtest.js";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=(v,c="CNY")=>{const cur=String(c||"CNY").toUpperCase();return new Intl.NumberFormat(cur==="USD"?"en-US":"zh-CN",{style:"currency",currency:cur==="USD"?"USD":"CNY",maximumFractionDigits:2}).format(Number(v)||0)};
const num=v=>Number(v||0).toLocaleString("en-US",{maximumFractionDigits:4}), iso=d=>new Date(d).toISOString().slice(0,10);
const defaults={cash:100000,initialCash:100000,positions:{},trades:[],recent:[],csv:{},settings:{apiBase:"",usdCny:7.2}};
let state;try{state=JSON.parse(localStorage.getItem("invest-sim")||"null")||structuredClone(defaults)}catch{state=structuredClone(defaults)}
state.settings=state.settings&&typeof state.settings==="object"?state.settings:{};
state.settings.apiBase=String(state.settings.apiBase||"").trim().replace(/\/$/,"");
state.settings.usdCny=Number(state.settings.usdCny)||7.2;
state.positions=state.positions&&typeof state.positions==="object"?state.positions:{};
state.trades=Array.isArray(state.trades)?state.trades:[];
state.recent=Array.isArray(state.recent)?state.recent:[];
state.csv=state.csv&&typeof state.csv==="object"?state.csv:{};
state.cash=Number.isFinite(Number(state.cash))?Number(state.cash):100000;
state.initialCash=Number.isFinite(Number(state.initialCash))?Number(state.initialCash):state.cash;
const save=()=>localStorage.setItem("invest-sim",JSON.stringify(state));
const toast=m=>{const t=$("#toast");t.textContent=m;t.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove("show"),2600)};
const api=()=>new DataAPI(state.settings);
function go(id){$$(".page").forEach(x=>x.classList.toggle("active",x.id===id));$$(".tab").forEach(x=>x.classList.toggle("active",x.dataset.go===id));render();scrollTo(0,0)}
$$("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go));
function sym(raw){const s=String(raw||"").trim().toUpperCase();if(/^\d{6}$/.test(s)){if(/^(60|68|5)/.test(s))return s+".SS";if(/^(00|30|15|16|18)/.test(s))return s+".SZ"}return s}
async function quote(s){return api().quote(sym(s))}
async function history(s,a,b){const k=sym(s),local=state.csv[k];if(local&&local.length){const x=local.filter(v=>(!a||v.date>=a)&&(!b||v.date<=b));if(x.length>1)return x}return api().history(k,a,b)}
function positionValue(){return Object.values(state.positions).reduce((a,p)=>a+(p.currency==="USD"?p.qty*p.price*Number(state.settings.usdCny||7.2):p.qty*p.price),0)}
function render(){
 const mv=positionValue(),tot=state.cash+mv;$("#cash").textContent=money(state.cash);$("#marketValue").textContent=money(mv);$("#totalAssets").textContent=money(tot);$("#portfolioCash").textContent=money(state.cash);$("#portfolioTotal").textContent=money(tot);
 const ps=Object.values(state.positions);
 $("#dashboardPositions").innerHTML=ps.length?ps.map(p=>'<div class="row"><span><b>'+p.symbol+'</b><small>'+num(p.qty)+' · 成本 '+num(p.avg)+'</small></span><b>'+money(p.qty*p.price,p.currency)+'</b></div>').join(""):'<div class="empty">还没有模拟持仓</div>';
 $("#positions").innerHTML=ps.length?ps.map(p=>'<div class="row"><span><b>'+p.symbol+'</b><small>'+num(p.qty)+' · 成本 '+num(p.avg)+' · 最新 '+num(p.price)+'</small></span><strong class="'+(p.price>=p.avg?"positive":"negative")+'">'+money((p.price-p.avg)*p.qty,p.currency)+'</strong></div>').join(""):'<div class="panel empty">暂无持仓</div>';
 $("#trades").innerHTML=state.trades.length?state.trades.slice().reverse().slice(0,50).map(t=>'<div class="row"><span><b>'+(t.side==="buy"?"买入":"卖出")+' '+t.symbol+'</b><small>'+new Date(t.time).toLocaleString()+' · '+num(t.qty)+' × '+num(t.price)+'</small></span><span>'+money(t.total,t.currency)+'</span></div>').join(""):'<div class="empty">暂无交易</div>';
 $("#recentSymbols").innerHTML=state.recent.map(s=>'<button class="chip" data-symbol="'+s+'">'+s+"</button>").join("")||'<span class="muted">暂无记录</span>';
 $$("[data-symbol]").forEach(b=>b.onclick=()=>{$("#symbolInput").value=b.dataset.symbol;$("#quoteForm").requestSubmit()});
 const keys=Object.keys(state.csv);$("#csvInfo").textContent=keys.length?keys.map(k=>k+": "+state.csv[k].length+" 条").join(" · "):"尚未导入数据";
}
$("#quoteForm").onsubmit=async e=>{e.preventDefault();const raw=$("#symbolInput").value.trim();if(!raw)return toast("请输入代码");try{toast("正在获取行情…");const q=await quote(raw),k=sym(raw),c=q.currency||"USD";state.recent=[k,...state.recent.filter(x=>x!==k)].slice(0,10);save();$("#quoteResult").innerHTML='<div class="panel"><div class="muted">'+q.symbol+" · "+q.name+'</div><div class="quote-main">'+(c==="USD"?"$":"¥")+num(q.price)+'</div><div class="'+(q.change>=0?"positive":"negative")+'">'+(q.change>=0?"+":"")+num(q.change)+"（"+(q.changePct>=0?"+":"")+q.changePct.toFixed(2)+"%）"+'</div><div class="asset-row"><span>最高 <b>'+num(q.high)+'</b></span><span>最低 <b>'+num(q.low)+'</b></span><span>币种 <b>'+c+"</b></span></div></div>";render()}catch(x){toast("行情获取失败："+x.message)}};
$("#tradeForm").onsubmit=async e=>{e.preventDefault();const k=sym($("#tradeSymbol").value),side=$("#tradeSide").value,qty=Number($("#tradeQty").value),fr=Math.max(0,Number($("#tradeFee").value)||0);if(!k||qty<=0)return toast("请填写交易信息");try{let price=Number($("#tradePrice").value),cur="CNY";if(!price){const q=await quote(k);price=q.price;cur=q.currency||"CNY"}const gross=price*qty,fee=gross*fr,fx=cur==="USD"?Number(state.settings.usdCny||7.2):1,cost=(gross+fee)*fx,proceeds=(gross-fee)*fx,p=state.positions[k]||{symbol:k,qty:0,avg:0,price,currency:cur};if(side==="buy"){if(cost>state.cash)return toast("现金不足");p.avg=(p.avg*p.qty+gross+fee)/(p.qty+qty);p.qty+=qty;state.cash-=cost}else{if(qty>p.qty)return toast("持仓不足");state.cash+=proceeds;p.qty-=qty}p.price=price;p.currency=cur;if(p.qty)state.positions[k]=p;else delete state.positions[k];state.trades.push({symbol:k,side,qty,price,total:gross,fee,currency:cur,cashImpact:side==="buy"?-cost:proceeds,time:Date.now()});save();render();toast("模拟交易已执行")}catch(x){toast("交易失败："+x.message)}};
function chart(a){if(!a.length)return"";const w=900,h=240,p=18,lo=Math.min(...a),hi=Math.max(...a),s=hi-lo||1,pts=a.map((v,i)=>p+i*(w-2*p)/Math.max(1,a.length-1)+","+((h-p)-(v-lo)/s*(h-2*p))).join(" ");return'<svg class="chart" viewBox="0 0 '+w+" "+h+'" preserveAspectRatio="none"><polyline points="'+pts+'" fill="none" stroke="currentColor" stroke-width="3"/></svg>'}
$("#backtestForm").onsubmit=async e=>{e.preventDefault();const k=sym($("#btSymbol").value),cap=Number($("#btCapital").value),a=$("#btStart").value,b=$("#btEnd").value,st=$("#btStrategy").value;if(!k||cap<=0||!a||!b)return toast("参数不完整");try{toast("正在下载历史数据…");const bars=await history(k,a,b);if(bars.length<2)throw Error("历史数据不足");const r=runBacktest(bars,{capital:cap,strategy:st,feeRate:Number($("#btFee").value)||0,slippage:Number($("#btSlippage").value)||0,position:Math.min(1,Number($("#btPosition").value)||1),riskFreeRate:0});$("#backtestResult").innerHTML='<div class="panel"><div class="metric-grid"><div class="metric"><small>期末资产</small><b>'+money(r.final)+'</b></div><div class="metric"><small>累计收益</small><b class="'+(r.cum>=0?"positive":"negative")+'">'+r.cum.toFixed(2)+'%</b></div><div class="metric"><small>年化收益</small><b>'+r.cagr.toFixed(2)+'%</b></div><div class="metric"><small>最大回撤</small><b class="negative">-'+r.maxDrawdown.toFixed(2)+'%</b></div><div class="metric"><small>Sharpe</small><b>'+r.sharpe.toFixed(2)+'</b></div><div class="metric"><small>年化波动</small><b>'+r.volatility.toFixed(2)+'%</b></div><div class="metric"><small>交易次数</small><b>'+r.trades+'</b></div><div class="metric"><small>数据点</small><b>'+bars.length+'</b></div></div><div class="chart-wrap">'+chart(r.curve)+'</div><p>已计入手续费、滑点和仓位比例；未完整模拟涨跌停、停牌、成交量约束及全部公司行为。</p></div>';toast("回测完成")}catch(x){toast("回测失败："+x.message)}};
function parseCSV(t){const l=t.replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean),h=l[0].split(",").map(x=>x.trim().toLowerCase()),di=h.indexOf("date"),ci=h.indexOf("close");if(di<0||ci<0)throw Error("必须有 date、close 列");const ix=k=>h.indexOf(k),o=[];for(const z of l.slice(1)){const a=z.split(","),c=Number(a[ci]);if(a[di]&&Number.isFinite(c))o.push({date:iso(a[di]),open:Number(a[ix("open")])||c,high:Number(a[ix("high")])||c,low:Number(a[ix("low")])||c,close:c,volume:Number(a[ix("volume")])||0})}return o.sort((a,b)=>a.date.localeCompare(b.date))}
$("#csvFile").onchange=async e=>{const f=e.target.files[0];if(!f)return;const k=prompt("请输入这份数据的代码，例如 AAPL 或 600519：");if(!k)return;try{const rows=parseCSV(await f.text());if(rows.length<2)throw Error("有效数据不足");state.csv[sym(k)]=rows;save();render();toast("CSV 导入完成")}catch(x){toast("CSV 导入失败："+x.message)}};
$("#clearCsvBtn").onclick=()=>{state.csv={};save();render();toast("本地历史数据已清除")};
$("#exportBtn").onclick=()=>{const a=document.createElement("a"),u=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:"application/json"}));a.href=u;a.download="investment-lab-backup.json";a.click();URL.revokeObjectURL(u)};
$("#importAccount").onchange=async e=>{try{const x=JSON.parse(await e.target.files[0].text());if(typeof x.cash!=="number"||!x.positions)throw Error("格式错误");if(!Number.isFinite(Number(x.cash))||!x.positions||typeof x.positions!=="object"||!Array.isArray(x.trades||[]))throw Error("账户结构无效");state.cash=Number(x.cash);state.initialCash=Number(x.initialCash)>0?Number(x.initialCash):state.cash;state.positions=x.positions;state.trades=x.trades;state.recent=Array.isArray(x.recent)?x.recent:[];state.csv=x.csv&&typeof x.csv==="object"?x.csv:{};state.settings={...state.settings,...(x.settings||{})};save();render();toast("账户已安全导入")}catch(x){toast("导入失败："+x.message)}};
$("#resetBtn").onclick=()=>{if(confirm("确定重置模拟账户？")){state.cash=state.initialCash;state.positions={};state.trades=[];save();render();toast("账户已重置")}};
$("#refreshBtn").onclick=async()=>{const ps=Object.values(state.positions);if(!ps.length)return toast("暂无持仓");let ok=0,fail=0;for(const p of ps){try{const q=await quote(p.symbol);p.price=q.price;p.currency=q.currency;ok++}catch{fail++}}save();render();toast(fail?("刷新完成："+ok+" 个成功，"+fail+" 个失败"):("刷新完成："+ok+" 个标的"))};
$("#settingsForm").onsubmit=e=>{e.preventDefault();state.settings.apiBase=$("#apiBase").value.trim().replace(/\/$/,"");state.settings.usdCny=Math.max(0.1,Number($("#usdCny").value)||7.2);const n=Number($("#initialCash").value);if(n>0&&!state.trades.length){state.initialCash=n;state.cash=n}save();toast("设置已保存")};
$("#apiBase").value=state.settings.apiBase||"";$("#usdCny").value=state.settings.usdCny;$("#initialCash").value=state.initialCash;const today=new Date(),end=iso(today),start=new Date(today);start.setFullYear(start.getFullYear()-5);$("#btStart").value=iso(start);$("#btEnd").value=end;render();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});
