import {DataAPI} from "./data.js";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=(v,c="CNY")=>{const cur=String(c||"CNY").toUpperCase();return new Intl.NumberFormat(cur==="USD"?"en-US":"zh-CN",{style:"currency",currency:cur==="USD"?"USD":"CNY",maximumFractionDigits:2}).format(Number(v)||0)};
const num=v=>Number(v||0).toLocaleString("en-US",{maximumFractionDigits:4}), iso=d=>new Date(d).toISOString().slice(0,10);
const state=JSON.parse(localStorage.getItem("invest-sim")||"null")||{cash:100000,initialCash:100000,positions:{},trades:[],recent:[],csv:{},settings:{apiBase:""}};
state.settings||={apiBase:"",usdCny:7.2};state.settings.usdCny=Number(state.settings.usdCny)||7.2;state.positions||={};state.trades||=[];state.recent||=[];state.csv||={};
const save=()=>localStorage.setItem("invest-sim",JSON.stringify(state));
const toast=m=>{const t=$("#toast");t.textContent=m;t.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove("show"),2600)};
const api=()=>new DataAPI(state.settings);
function go(id){$$(".page").forEach(x=>x.classList.toggle("active",x.id===id));$$(".tab").forEach(x=>x.classList.toggle("active",x.dataset.go===id));render();scrollTo(0,0)}
$$("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go));
function sym(raw){const s=String(raw||"").trim().toUpperCase();if(/^\d{6}$/.test(s)){if(/^(60|68|5)/.test(s))return s+".SS";if(/^(00|30|15|16|18)/.test(s))return s+".SZ"}return s}
async function quote(s){return api().quote(sym(s))}
async function history(s,a,b){const k=sym(s),local=state.csv[k];if(local&&local.length){const x=local.filter(v=>(!a||v.date>=a)&&(!b||v.date<=b));if(x.length>1)return x}return api().history(k,a,b)}
function positionValue(){return Object.values(state.positions).reduce((a,p)=>a+(p.currency==="USD"?p.qty*p.price*Number(state.settings.usdCny||7.2):p.qty*p.price),0)}
function render(){
 const mv=positionValue(),tot=state.cash+mv;$("#cash").textContent=money(state.cash);$("#marketValue").textContent=money(mv);$("#totalAssets").textContent=money(tot);$("#portfolioCash").textContent=money(state.cash);$("#portfolioTotal").textContent=money(tot);
 const ps=Object.values(state.positions);
 $("#dashboardPositions").innerHTML=ps.length?ps.map(p=>'<div class="row"><span><b>'+p.symbol+'</b><small>'+num(p.qty)+' · 成本 '+num(p.avg)+'</small></span><b>'+money(p.qty*p.price,p.currency)+'</b></div>').join(""):'<div class="empty">还没有模拟持仓</div>';
 $("#positions").innerHTML=ps.length?ps.map(p=>'<div class="row"><span><b>'+p.symbol+'</b><small>'+num(p.qty)+' · 成本 '+num(p.avg)+' · 最新 '+num(p.price)+'</small></span><strong class="'+(p.price>=p.avg?"positive":"negative")+'">'+money((p.price-p.avg)*p.qty,p.currency)+'</strong></div>').join(""):'<div class="panel empty">暂无持仓</div>';
 $("#trades").innerHTML=state.trades.length?state.trades.slice().reverse().slice(0,50).map(t=>'<div class="row"><span><b>'+(t.side==="buy"?"买入":"卖出")+' '+t.symbol+'</b><small>'+new Date(t.time).toLocaleString()+' · '+num(t.qty)+' × '+num(t.price)+'</small></span><span>'+money(t.total,t.currency)+'</span></div>').join(""):'<div class="empty">暂无交易</div>';
 $("#recentSymbols").innerHTML=state.recent.map(s=>'<button class="chip" data-symbol="'+s+'">'+s+"</button>").join("")||'<span class="muted">暂无记录</span>';
 $$("[data-symbol]").forEach(b=>b.onclick=()=>{$("#symbolInput").value=b.dataset.symbol;$("#quoteForm").requestSubmit()});
 const keys=Object.keys(state.csv);$("#csvInfo").textContent=keys.length?keys.map(k=>k+": "+state.csv[k].length+" 条").join(" · "):"尚未导入数据";
}
$("#quoteForm").onsubmit=async e=>{e.preventDefault();const raw=$("#symbolInput").value.trim();if(!raw)return toast("请输入代码");try{toast("正在获取行情…");const q=await quote(raw),k=sym(raw),c=q.currency||"USD";state.recent=[k,...state.recent.filter(x=>x!==k)].slice(0,10);save();$("#quoteResult").innerHTML='<div class="panel"><div class="muted">'+q.symbol+" · "+q.name+'</div><div class="quote-main">'+(c==="USD"?"$":"¥")+num(q.price)+'</div><div class="'+(q.change>=0?"positive":"negative")+'">'+(q.change>=0?"+":"")+num(q.change)+"（"+(q.changePct>=0?"+":"")+q.changePct.toFixed(2)+"%）"+'</div><div class="asset-row"><span>最高 <b>'+num(q.high)+'</b></span><span>最低 <b>'+num(q.low)+'</b></span><span>币种 <b>'+c+"</b></span></div></div>";render()}catch(x){toast("行情获取失败："+x.message)}};
$("#tradeForm").onsubmit=async e=>{e.preventDefault();const k=sym($("#tradeSymbol").value),side=$("#tradeSide").value,qty=Number($("#tradeQty").value),fr=Math.max(0,Number($("#tradeFee").value)||0);if(!k||qty<=0)return toast("请填写交易信息");try{let price=Number($("#tradePrice").value),cur="CNY";if(!price){const q=await quote(k);price=q.price;cur=q.currency||"CNY"}const gross=price*qty,fee=gross*fr,p=state.positions[k]||{symbol:k,qty:0,avg:0,price,currency:cur};if(side==="buy"){if(gross+fee>state.cash)return toast("现金不足");p.avg=(p.avg*p.qty+gross+fee)/(p.qty+qty);p.qty+=qty;state.cash-=gross+fee}else{if(qty>p.qty)return toast("持仓不足");state.cash+=gross-fee;p.qty-=qty}p.price=price;p.currency=cur;if(p.qty)state.positions[k]=p;else delete state.positions[k];state.trades.push({symbol:k,side,qty,price,total:gross,fee,currency:cur,time:Date.now()});save();render();toast("模拟交易已执行")}catch(x){toast("交易失败："+x.message)}};
const avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
const sd=a=>{if(a.length<2)return 0;const m=avg(a);return Math.sqrt(avg(a.map(x=>(x-m)**2)))};
const dd=a=>{let peak=0,out=0;for(const x of a){peak=Math.max(peak,x);if(peak)out=Math.max(out,(peak-x)/peak)}return out};
function bt(bars,capital,strategy,fee,slip,pos){let cash=capital,sh=0,curve=[],trades=0;const buy=p=>p*(1+slip),sell=p=>p*(1-slip);for(let i=0;i<bars.length;i++){const p=bars[i].close;if(strategy==="buyhold"&&i===0){const inv=cash*pos,px=buy(p);sh=inv/(px*(1+fee));cash-=sh*px*(1+fee);trades++}if(strategy==="dca"&&i%21===0){const inv=Math.min(cash,capital/12*pos),px=buy(p),n=inv/(px*(1+fee));sh+=n;cash-=n*px*(1+fee);trades++}if(strategy==="ma"&&i>=60){const a=avg(bars.slice(i-20,i).map(x=>x.close)),b=avg(bars.slice(i-60,i).map(x=>x.close));if(a>b&&!sh){const inv=cash*pos,px=buy(p);sh=inv/(px*(1+fee));cash-=sh*px*(1+fee);trades++}else if(a<b&&sh){cash+=sh*sell(p)*(1-fee);sh=0;trades++}}if(strategy==="rsi"&&i>=14){let g=[],l=[];for(let j=i-13;j<=i;j++){const d=bars[j].close-bars[j-1].close;g.push(Math.max(d,0));l.push(Math.max(-d,0))}const rs=avg(l)?avg(g)/avg(l):100,r=100-100/(1+rs);if(r<30&&!sh){const inv=cash*pos,px=buy(p);sh=inv/(px*(1+fee));cash-=sh*px*(1+fee);trades++}else if(r>70&&sh){cash+=sh*sell(p)*(1-fee);sh=0;trades++}}curve.push(cash+sh*p)}const final=curve.at(-1),years=Math.max(1,(new Date(bars.at(-1).date)-new Date(bars[0].date))/31557600000),ret=curve.slice(1).map((v,i)=>curve[i]?v/curve[i]-1:0);return{final,ret:(final/capital-1)*100,cagr:(Math.pow(final/capital,1/years)-1)*100,dd:dd(curve)*100,sh:sd(ret)?avg(ret)/sd(ret)*Math.sqrt(252):0,vol:sd(ret)*Math.sqrt(252)*100,trades,curve}}
function chart(a){if(!a.length)return"";const w=900,h=240,p=18,lo=Math.min(...a),hi=Math.max(...a),s=hi-lo||1,pts=a.map((v,i)=>p+i*(w-2*p)/Math.max(1,a.length-1)+","+((h-p)-(v-lo)/s*(h-2*p))).join(" ");return'<svg class="chart" viewBox="0 0 '+w+" "+h+'" preserveAspectRatio="none"><polyline points="'+pts+'" fill="none" stroke="currentColor" stroke-width="3"/></svg>'}
$("#backtestForm").onsubmit=async e=>{e.preventDefault();const k=sym($("#btSymbol").value),cap=Number($("#btCapital").value),a=$("#btStart").value,b=$("#btEnd").value,st=$("#btStrategy").value;if(!k||cap<=0||!a||!b)return toast("参数不完整");try{toast("正在下载历史数据…");const bars=await history(k,a,b);if(bars.length<2)throw Error("历史数据不足");const r=bt(bars,cap,st,Number($("#btFee").value)||0,Number($("#btSlippage").value)||0,Math.min(1,Number($("#btPosition").value)||1));$("#backtestResult").innerHTML='<div class="panel"><div class="metric-grid"><div class="metric"><small>期末资产</small><b>'+money(r.final)+'</b></div><div class="metric"><small>累计收益</small><b class="'+(r.ret>=0?"positive":"negative")+'">'+r.ret.toFixed(2)+'%</b></div><div class="metric"><small>年化收益</small><b>'+r.cagr.toFixed(2)+'%</b></div><div class="metric"><small>最大回撤</small><b class="negative">-'+r.dd.toFixed(2)+'%</b></div><div class="metric"><small>Sharpe</small><b>'+r.sh.toFixed(2)+'</b></div><div class="metric"><small>年化波动</small><b>'+r.vol.toFixed(2)+'%</b></div><div class="metric"><small>交易次数</small><b>'+r.trades+'</b></div><div class="metric"><small>数据点</small><b>'+bars.length+'</b></div></div><div class="chart-wrap">'+chart(r.curve)+'</div><p>已计入手续费、滑点和仓位比例；未完整模拟涨跌停、停牌、成交量约束及全部公司行为。</p></div>';toast("回测完成")}catch(x){toast("回测失败："+x.message)}};
function parseCSV(t){const l=t.replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean),h=l[0].split(",").map(x=>x.trim().toLowerCase()),di=h.indexOf("date"),ci=h.indexOf("close");if(di<0||ci<0)throw Error("必须有 date、close 列");const ix=k=>h.indexOf(k),o=[];for(const z of l.slice(1)){const a=z.split(","),c=Number(a[ci]);if(a[di]&&Number.isFinite(c))o.push({date:iso(a[di]),open:Number(a[ix("open")])||c,high:Number(a[ix("high")])||c,low:Number(a[ix("low")])||c,close:c,volume:Number(a[ix("volume")])||0})}return o.sort((a,b)=>a.date.localeCompare(b.date))}
$("#csvFile").onchange=async e=>{const f=e.target.files[0];if(!f)return;const k=prompt("请输入这份数据的代码，例如 AAPL 或 600519：");if(!k)return;try{const rows=parseCSV(await f.text());if(rows.length<2)throw Error("有效数据不足");state.csv[sym(k)]=rows;save();render();toast("CSV 导入完成")}catch(x){toast("CSV 导入失败："+x.message)}};
$("#clearCsvBtn").onclick=()=>{state.csv={};save();render();toast("本地历史数据已清除")};
$("#exportBtn").onclick=()=>{const a=document.createElement("a"),u=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:"application/json"}));a.href=u;a.download="investment-lab-backup.json";a.click();URL.revokeObjectURL(u)};
$("#importAccount").onchange=async e=>{try{const x=JSON.parse(await e.target.files[0].text());if(typeof x.cash!=="number"||!x.positions)throw Error("格式错误");Object.assign(state,x);save();render();toast("账户已导入")}catch(x){toast("导入失败："+x.message)}};
$("#resetBtn").onclick=()=>{if(confirm("确定重置模拟账户？")){state.cash=state.initialCash;state.positions={};state.trades=[];save();render();toast("账户已重置")}};
$("#refreshBtn").onclick=async()=>{try{for(const p of Object.values(state.positions)){const q=await quote(p.symbol);p.price=q.price;p.currency=q.currency}save();render();toast("行情已刷新")}catch(x){toast("刷新失败："+x.message)}};
$("#settingsForm").onsubmit=e=>{e.preventDefault();state.settings.apiBase=$("#apiBase").value.trim().replace(/\/$/,"");const n=Number($("#initialCash").value);if(n>0&&!state.trades.length){state.initialCash=n;state.cash=n}save();toast("设置已保存")};
$("#apiBase").value=state.settings.apiBase||"";$("#initialCash").value=state.initialCash;const today=new Date(),end=iso(today),start=new Date(today);start.setFullYear(start.getFullYear()-5);$("#btStart").value=iso(start);$("#btEnd").value=end;render();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});
